# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/milutin/Predavanje/ZI/projekatZI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/milutin/Predavanje/ZI/projekatZI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/milutin/Predavanje/ZI/projekatZI/CMakeFiles /home/milutin/Predavanje/ZI/projekatZI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/milutin/Predavanje/ZI/projekatZI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projekatZI

# Build rule for target.
projekatZI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projekatZI
.PHONY : projekatZI

# fast build rule for target.
projekatZI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/build
.PHONY : projekatZI/fast

#=============================================================================
# Target rules for targets named projekatZI_autogen_timestamp_deps

# Build rule for target.
projekatZI_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projekatZI_autogen_timestamp_deps
.PHONY : projekatZI_autogen_timestamp_deps

# fast build rule for target.
projekatZI_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI_autogen_timestamp_deps.dir/build.make CMakeFiles/projekatZI_autogen_timestamp_deps.dir/build
.PHONY : projekatZI_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named projekatZI_autogen

# Build rule for target.
projekatZI_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 projekatZI_autogen
.PHONY : projekatZI_autogen

# fast build rule for target.
projekatZI_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI_autogen.dir/build.make CMakeFiles/projekatZI_autogen.dir/build
.PHONY : projekatZI_autogen/fast

countdown.o: countdown.cpp.o
.PHONY : countdown.o

# target to build an object file
countdown.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/countdown.cpp.o
.PHONY : countdown.cpp.o

countdown.i: countdown.cpp.i
.PHONY : countdown.i

# target to preprocess a source file
countdown.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/countdown.cpp.i
.PHONY : countdown.cpp.i

countdown.s: countdown.cpp.s
.PHONY : countdown.s

# target to generate assembly for a file
countdown.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/countdown.cpp.s
.PHONY : countdown.cpp.s

enigmafileencryptor.o: enigmafileencryptor.cpp.o
.PHONY : enigmafileencryptor.o

# target to build an object file
enigmafileencryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/enigmafileencryptor.cpp.o
.PHONY : enigmafileencryptor.cpp.o

enigmafileencryptor.i: enigmafileencryptor.cpp.i
.PHONY : enigmafileencryptor.i

# target to preprocess a source file
enigmafileencryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/enigmafileencryptor.cpp.i
.PHONY : enigmafileencryptor.cpp.i

enigmafileencryptor.s: enigmafileencryptor.cpp.s
.PHONY : enigmafileencryptor.s

# target to generate assembly for a file
enigmafileencryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/enigmafileencryptor.cpp.s
.PHONY : enigmafileencryptor.cpp.s

fileencryptor.o: fileencryptor.cpp.o
.PHONY : fileencryptor.o

# target to build an object file
fileencryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/fileencryptor.cpp.o
.PHONY : fileencryptor.cpp.o

fileencryptor.i: fileencryptor.cpp.i
.PHONY : fileencryptor.i

# target to preprocess a source file
fileencryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/fileencryptor.cpp.i
.PHONY : fileencryptor.cpp.i

fileencryptor.s: fileencryptor.cpp.s
.PHONY : fileencryptor.s

# target to generate assembly for a file
fileencryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/fileencryptor.cpp.s
.PHONY : fileencryptor.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/main.cpp.s
.PHONY : main.cpp.s

projekatZI_autogen/mocs_compilation.o: projekatZI_autogen/mocs_compilation.cpp.o
.PHONY : projekatZI_autogen/mocs_compilation.o

# target to build an object file
projekatZI_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/projekatZI_autogen/mocs_compilation.cpp.o
.PHONY : projekatZI_autogen/mocs_compilation.cpp.o

projekatZI_autogen/mocs_compilation.i: projekatZI_autogen/mocs_compilation.cpp.i
.PHONY : projekatZI_autogen/mocs_compilation.i

# target to preprocess a source file
projekatZI_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/projekatZI_autogen/mocs_compilation.cpp.i
.PHONY : projekatZI_autogen/mocs_compilation.cpp.i

projekatZI_autogen/mocs_compilation.s: projekatZI_autogen/mocs_compilation.cpp.s
.PHONY : projekatZI_autogen/mocs_compilation.s

# target to generate assembly for a file
projekatZI_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/projekatZI_autogen/mocs_compilation.cpp.s
.PHONY : projekatZI_autogen/mocs_compilation.cpp.s

qwriteinfile.o: qwriteinfile.cpp.o
.PHONY : qwriteinfile.o

# target to build an object file
qwriteinfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/qwriteinfile.cpp.o
.PHONY : qwriteinfile.cpp.o

qwriteinfile.i: qwriteinfile.cpp.i
.PHONY : qwriteinfile.i

# target to preprocess a source file
qwriteinfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/qwriteinfile.cpp.i
.PHONY : qwriteinfile.cpp.i

qwriteinfile.s: qwriteinfile.cpp.s
.PHONY : qwriteinfile.s

# target to generate assembly for a file
qwriteinfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/qwriteinfile.cpp.s
.PHONY : qwriteinfile.cpp.s

symetricfileencryptor.o: symetricfileencryptor.cpp.o
.PHONY : symetricfileencryptor.o

# target to build an object file
symetricfileencryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/symetricfileencryptor.cpp.o
.PHONY : symetricfileencryptor.cpp.o

symetricfileencryptor.i: symetricfileencryptor.cpp.i
.PHONY : symetricfileencryptor.i

# target to preprocess a source file
symetricfileencryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/symetricfileencryptor.cpp.i
.PHONY : symetricfileencryptor.cpp.i

symetricfileencryptor.s: symetricfileencryptor.cpp.s
.PHONY : symetricfileencryptor.s

# target to generate assembly for a file
symetricfileencryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/symetricfileencryptor.cpp.s
.PHONY : symetricfileencryptor.cpp.s

threadencryptor.o: threadencryptor.cpp.o
.PHONY : threadencryptor.o

# target to build an object file
threadencryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadencryptor.cpp.o
.PHONY : threadencryptor.cpp.o

threadencryptor.i: threadencryptor.cpp.i
.PHONY : threadencryptor.i

# target to preprocess a source file
threadencryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadencryptor.cpp.i
.PHONY : threadencryptor.cpp.i

threadencryptor.s: threadencryptor.cpp.s
.PHONY : threadencryptor.s

# target to generate assembly for a file
threadencryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadencryptor.cpp.s
.PHONY : threadencryptor.cpp.s

threadxxteadecryptor.o: threadxxteadecryptor.cpp.o
.PHONY : threadxxteadecryptor.o

# target to build an object file
threadxxteadecryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadxxteadecryptor.cpp.o
.PHONY : threadxxteadecryptor.cpp.o

threadxxteadecryptor.i: threadxxteadecryptor.cpp.i
.PHONY : threadxxteadecryptor.i

# target to preprocess a source file
threadxxteadecryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadxxteadecryptor.cpp.i
.PHONY : threadxxteadecryptor.cpp.i

threadxxteadecryptor.s: threadxxteadecryptor.cpp.s
.PHONY : threadxxteadecryptor.s

# target to generate assembly for a file
threadxxteadecryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/threadxxteadecryptor.cpp.s
.PHONY : threadxxteadecryptor.cpp.s

tigerhash.o: tigerhash.cpp.o
.PHONY : tigerhash.o

# target to build an object file
tigerhash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/tigerhash.cpp.o
.PHONY : tigerhash.cpp.o

tigerhash.i: tigerhash.cpp.i
.PHONY : tigerhash.i

# target to preprocess a source file
tigerhash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/tigerhash.cpp.i
.PHONY : tigerhash.cpp.i

tigerhash.s: tigerhash.cpp.s
.PHONY : tigerhash.s

# target to generate assembly for a file
tigerhash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/tigerhash.cpp.s
.PHONY : tigerhash.cpp.s

widget.o: widget.cpp.o
.PHONY : widget.o

# target to build an object file
widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/widget.cpp.o
.PHONY : widget.cpp.o

widget.i: widget.cpp.i
.PHONY : widget.i

# target to preprocess a source file
widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/widget.cpp.i
.PHONY : widget.cpp.i

widget.s: widget.cpp.s
.PHONY : widget.s

# target to generate assembly for a file
widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/widget.cpp.s
.PHONY : widget.cpp.s

xxteacfb.o: xxteacfb.cpp.o
.PHONY : xxteacfb.o

# target to build an object file
xxteacfb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteacfb.cpp.o
.PHONY : xxteacfb.cpp.o

xxteacfb.i: xxteacfb.cpp.i
.PHONY : xxteacfb.i

# target to preprocess a source file
xxteacfb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteacfb.cpp.i
.PHONY : xxteacfb.cpp.i

xxteacfb.s: xxteacfb.cpp.s
.PHONY : xxteacfb.s

# target to generate assembly for a file
xxteacfb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteacfb.cpp.s
.PHONY : xxteacfb.cpp.s

xxteaencryptor.o: xxteaencryptor.cpp.o
.PHONY : xxteaencryptor.o

# target to build an object file
xxteaencryptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteaencryptor.cpp.o
.PHONY : xxteaencryptor.cpp.o

xxteaencryptor.i: xxteaencryptor.cpp.i
.PHONY : xxteaencryptor.i

# target to preprocess a source file
xxteaencryptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteaencryptor.cpp.i
.PHONY : xxteaencryptor.cpp.i

xxteaencryptor.s: xxteaencryptor.cpp.s
.PHONY : xxteaencryptor.s

# target to generate assembly for a file
xxteaencryptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/projekatZI.dir/build.make CMakeFiles/projekatZI.dir/xxteaencryptor.cpp.s
.PHONY : xxteaencryptor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... projekatZI_autogen"
	@echo "... projekatZI_autogen_timestamp_deps"
	@echo "... projekatZI"
	@echo "... countdown.o"
	@echo "... countdown.i"
	@echo "... countdown.s"
	@echo "... enigmafileencryptor.o"
	@echo "... enigmafileencryptor.i"
	@echo "... enigmafileencryptor.s"
	@echo "... fileencryptor.o"
	@echo "... fileencryptor.i"
	@echo "... fileencryptor.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... projekatZI_autogen/mocs_compilation.o"
	@echo "... projekatZI_autogen/mocs_compilation.i"
	@echo "... projekatZI_autogen/mocs_compilation.s"
	@echo "... qwriteinfile.o"
	@echo "... qwriteinfile.i"
	@echo "... qwriteinfile.s"
	@echo "... symetricfileencryptor.o"
	@echo "... symetricfileencryptor.i"
	@echo "... symetricfileencryptor.s"
	@echo "... threadencryptor.o"
	@echo "... threadencryptor.i"
	@echo "... threadencryptor.s"
	@echo "... threadxxteadecryptor.o"
	@echo "... threadxxteadecryptor.i"
	@echo "... threadxxteadecryptor.s"
	@echo "... tigerhash.o"
	@echo "... tigerhash.i"
	@echo "... tigerhash.s"
	@echo "... widget.o"
	@echo "... widget.i"
	@echo "... widget.s"
	@echo "... xxteacfb.o"
	@echo "... xxteacfb.i"
	@echo "... xxteacfb.s"
	@echo "... xxteaencryptor.o"
	@echo "... xxteaencryptor.i"
	@echo "... xxteaencryptor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

